import pdf from "../Descargas/Archivos-Downloand/AUT_DSCTO_DESCUENTO_COPERE.pdf";
import pdf1 from "../Descargas/Archivos-Downloand/AUT_DSCTO_DESCUENTO_CPMP.pdf";
import pdf2 from "../Descargas/Archivos-Downloand/AUTORIZACION_DE_DESCUENTO_SUB_CAFAE_EP.pdf";
import pdf3 from "../Descargas/Archivos-Downloand/CARTA_DECLARATORIA_FSCEC.pdf";
import pdf4 from "../Descargas/Archivos-Downloand/COMPROMISO_PAGO_OBLIGATORIO.pdf";
import pdf5 from "../Descargas/Archivos-Downloand/CONTRATO FIANZA.pdf";
import pdf6 from "../Descargas/Archivos-Downloand/DOC_NO_REVOCATORIA_CPMP.pdf";
import pdf7 from "../Descargas/Archivos-Downloand/FOLLETO_FSCEC.pdf";
import pdf8 from "../Descargas/Archivos-Downloand/SOLICITUD_FSCEC.pdf";
import pdf9 from "../Descargas/Archivos-Downloand/SOLICITUD_FSRyC_VARIOS.pdf";
import pdf10 from "../Descargas/Archivos-Downloand/SOLICITUD_PRESTAMO.pdf";
import pdf11 from "../Descargas/Archivos-Downloand/SOLICITUD_VARIOS.pdf";